name: Grade Exams

on:
  workflow_dispatch:
    inputs:
      EXAM_ID:
        description: 'The ID of the exam to grade'
        required: true

jobs:
  grade-exam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin google-generativeai

      - name: Decode FIREBASE_ADMINSDK_JSON
        run: echo "${{ secrets.FIREBASE_ADMINSDK_JSON }}" | base64 --decode > firebase-adminsdk.json

      - name: Set environment variables
        run: |
          echo "EXAM_ID=${{ github.event.inputs.EXAM_ID }}" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_ADMINSDK_JSON_PATH=firebase-adminsdk.json" >> $GITHUB_ENV

      - name: Run grading script
        run: python lib/exam_grading.py
